-- MySQL Script generated by MySQL Workbench
-- Wed Jan 31 20:18:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema futibaClub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema futibaClub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `futibaClub` DEFAULT CHARACTER SET utf8 ;
USE `futibaClub` ;

-- -----------------------------------------------------
-- Table `futibaClub`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futibaClub`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(245) NULL,
  `passwd` VARCHAR(245) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futibaClub`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futibaClub`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(245) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futibaClub`.`groups_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futibaClub`.`groups_user` (
  `id` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  `groups_id` INT NOT NULL,
  `role` VARCHAR(45) NULL,
  INDEX `fk_groups_user_users_idx` (`users_id` ASC),
  INDEX `fk_groups_user_groups1_idx` (`groups_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_groups_user_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `futibaClub`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groups_user_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `futibaClub`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futibaClub`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futibaClub`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team_a` VARCHAR(245) NULL,
  `team_b` VARCHAR(245) NULL,
  `result_a` INT NULL,
  `result_b` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futibaClub`.`quessing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futibaClub`.`quessing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `result_a` INT NULL,
  `result_b` INT NULL,
  `score` INT NULL,
  `games_id` INT NOT NULL,
  `groups_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `groups_id`, `users_id`),
  INDEX `fk_quessing_games1_idx` (`games_id` ASC),
  INDEX `fk_quessing_groups1_idx` (`groups_id` ASC),
  INDEX `fk_quessing_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_quessing_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `futibaClub`.`games` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_quessing_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `futibaClub`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_quessing_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `futibaClub`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futibaClub`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futibaClub`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comments` TEXT NULL,
  `quessing_id` INT NOT NULL,
  `quessing_groups_id` INT NOT NULL,
  `quessing_users_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `quessing_id`, `quessing_groups_id`, `quessing_users_id`, `users_id`),
  INDEX `fk_comments_quessing1_idx` (`quessing_id` ASC, `quessing_groups_id` ASC, `quessing_users_id` ASC),
  INDEX `fk_comments_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_comments_quessing1`
    FOREIGN KEY (`quessing_id` , `quessing_groups_id` , `quessing_users_id`)
    REFERENCES `futibaClub`.`quessing` (`id` , `groups_id` , `users_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `futibaClub`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
